String.toLocaleString({
	"en": {
		
	},
	
	"ru": {
		"Log In": "Войти",
		"Log Out": "Выйти",
		"File": "Файл",
		"Languages": "Язык",
		"Edit": "Редактровать",
		"Copy": "Скопировать",
		"Paste": "Вставить",
		"Duplicate": "Дублировать",
		"Delete": "Удалить",
		"Save Copy": "Сохранить копию",
		"Publish": "Опубликовать",
		"Set Permissions": "Установить права",
		"Save Now": "Сохранить сейчас",	
		"Save to Inventory": "Сохранить в инвентарий",
		"Select": "Выбрать",
		"Select By Name": "Выбрать по имени",
		"Pick": "Выбрать",
		"Select None": "Снять выбор",
		"Select Scene": "Выбрать сцену",
		"Select by clicking": "Выбор по нажатию",
		"Transform": "Трансформировать",
		"Move": "Перемещать",
		"Rotate": "Вращать",
		"Scale": "Масштабировать",
		"Multi": "Все трансформации",
		"Local Coords": "Локальные координаты",
		"World Coords": "Глобальные координаты",
		"Snaps": "Сетка",
		"Large": "Большая",
		"Medium": "Средняя",
		"Small": "Маленькая",
		"Off": "Выключена",
		"Move Tool": "Перемещать",
		"Rotate Tool": "Вращать",
		"Scale Tool": "Масштабировать",
		"Use Local Coordinates": "Локальные координаты",
		"Use World Coordinates": "Глобальные координаты",
		"Camera": "Камера",
		"Focus Selected": "Фокурсировка на выбранном",
		"Share Camera View": "Разделить камеру",
		"Activate Camera": "Активировать камеру",
		"Default Cameras": "Камера по умолчанию",
		"Orbit": "Орбита",
		"Free": "Свободная",
		"Avatar View": "Вид от аватара",
		"Navigate": "Навигационная",
		"Fly": "Облет",
		"None": "Нет",
		"Hierarchy": "Иерархия",
		"Link": "Связать",
		"Unlink": "Удалить связь",
		"Select Parent": "Выбрать родителя",
		"Grouping": "Группировка",
		"Group": "Сгруппировать",
		"Ungroup": "Разгруппировать",
		"Open Group": "Открыть группу",
		"Close Group": "Закрыть группу",
		"Orbit Camera": "Камера орбита",
		"Navigation Camera": "Камера навигационная",
		"Free Camera": "Камера свободная",
		"Focus to selected object": "Сфокурсировать на выбранный объект",
		"First Person Camera": "Камера от первого лица",
		"Create": "Создать",
		"Primitives": "Примитивы",
		"Sphere": "Сфера",
		"Box": "Куб",
		"Plane": "Плоскость",
		"Cylinder": "Цилиндр",
		"Cone": "Конус",
		"Create Sphere": "Сфера",
		"Create Box": "Куб",
		"Create Plane": "Плоскость",
		"Create Cylinder": "Цилиндр",
		"Create Cone": "Конус",
		"Text": "Текст",
		"Torus": "Тор",
		"Shapes": "Фигуры",
		"Line": "Линия",
		"Circle": "Круг",
		"Star": "Звезда",
		"Rectangle": "Прямоугольник",
		"L Section": "L секция",
		"T Section": "T секция",
		"Modifiers": "Модификаторы",
		"Bend": "Сгибание",
		"Twist": "Скручивание",
		"Taper": "Сужение",
		"Perlin Noise": "Шум Перлина",
		"Simplex Noise": "Шум симплексный",
		"Offset": "Смещение",
		"Stretch": "Растяжение",
		"Push": "Вдавление",
		"UVMap": "UV карта",
		"Center Pivot": "Центр вращения",
		"Extrude": "Выдавливание",
		"Lathe": "Станок",
		"Behaviors": "Поведения",
		"New Behavior": "Новое поведение",
		"Rotator": "Поворотное устройство",
		"Orbit": "Орбита",
		"Hyper link": "Гиперссылка",
		"Hover label": "Знак на наведение",
		"Path Follow": "Следовать пути",
		"Clamp To Ground": "Заземлить",
		"LookAt": "Смотреть на..",
		"Seek": "Стремиться",
		"Dialog System":"Система диалогов",
		"Lights": "Свет",
		"Point": "Точечный",
		"Light": "Местный",
		"Directional": "Направленный",
		"Particles": "Система частиц",
		"Basic": "Простая",
		"Cameras": "Камеры",
		"Perspective": "Перспективная",
		"Orthographic (comming soon!)": "Ортографическая (скоро)",
		"Terrain": "Генератор земли",
		"Load Mesh URL": "Загрузить модель из ссылки",
		"Tools": "Инструменты",
		"Align": "Выравнять",
		"Block Painter": "Рисование блоками",
		"SnapMove": "Двигать по сетке",
		"Spline Tools": "Сплайн инструменты",
		"Windows": "Окна",
		"Chat": "Чат",
		"Users": "Пользователи",
		"Material Editor": "Редактор материалов",
		"Script Editor": "Редактор скриптов",
		"Object Properties": "Параметры объекта",
		"Models": "Модели",
		"Inventory": "Инвентарий",
		"Public Inventory": "Публичный инвентарий",
		"Show Hierarchy": "Показать иерархию объектов",
		"Rendering": "Рендеринг",
		"Toggle Wireframe": "Сетка",
		"Toggle Glyphs": "Показать иконки",
		"Toggle Sun Shadows": "Тени от солнца",
		"Toggle Full Screen": "Полный экран",
		"Toggle Stats": "Статистика",
		"Toggle Interpolation": "Интерполяция движений",
		"Batching": "",
		"Force Batch All": "",
		"Toggle Dynamic Batching": "",
		"Location": "Место",
		"Go to Position...": "Перейти в позицию...",
		"Go to Placemark...": "Перейти в место...",
		"Add Placemark...": "Добавить место...",
		"Move to ground": "Опуститься на землю",
		"Help": "Помощь",
		"About": "О программе",
		"Browse All Topics...": "Открыть все темы...",
		"Test Latency": "Тестировать сеть",
		"Show Users Window": "Окно пользователей",
		"Show Chat Window": "Чат",
		"Show Material Editor Window": "Редактор материалов",
		"Show Script Editor Window": "Редактор скриптов",
		"Show Object Properties Window": "Параметры объекта",
		"Show Inventory Window": "Инвентарий",
		"Show Hierarchy Window": "Иерархия объектов",
		"Share": "Share", //XXX - Missing translation
		"Set World Thumbnail": "Set World Thumbnail", //XXX - Missing translation
		"Reset Transforms": "Reset Transforms", //XXX - Missing translation
		"Save Selected": "Save Selected", //XXX - Missing translation
		"Publish Selected": "Publish Selected", //XXX - Missing translation
	},


	"es_ES": {
		"Log In": "Iniciar Sesión",
		"Log Out": "Finalizar Sesión",
		"File": "Archivo",
		"Share": "Compartir",
		"Set World Thumbnail": "Establecer miniatura (vista previa)",
		"Languages": "Idiomas",
		"Edit": "Editar",
		"Copy": "Copiar",
		"Paste": "Pegar",
		"Duplicate": "Duplicar",
		"Delete": "Borrar",
		"Save Copy": "Guardar Copia",
		"Publish": "Publicar",
		"Set Permissions": "Establecer Permisos",
		"Save Now": "Guardar Ahora",	
		"Save to Inventory": "Guardar al Inventario",
		"Select": "Seleccionar",
		"Select By Name": "Seleccionar por Nombre",
		"Pick": "Escoger",
		"Select None": "Deseleccionar todo",
		"Select Scene": "Escena",
		"Select by clicking": "Seleccionar Haciendo clic",
		"Save Selected": "Guardar Selección",
		"Publish Selected": "Publicar Selección",
		"Transform": "Тransformar",
		"Move": "Mover",
		"Rotate": "Rotar",
		"Scale": "Escalar",
		"Multi": "Multi",
		"Local Coords": "Coordenadas Locales",
		"World Coords": "Coordenadas respecto al Mundo",
		"Snaps": "Ajustar",
		"Large": "Grande",
		"Medium": "Medio",
		"Small": "Pequeño",
		"Off": "Apagado",
		"Reset Transforms": "Deshacer Transformaciones",
		"Move Tool": "Herramienta Mover",
		"Rotate Tool": "Herramienta Rotar",
		"Scale Tool": "Herramienta Escalar",
		"Use Local Coordinates": "Utilizar Coordenadas Locales",
		"Use World Coordinates": "Utilizar Coordenadas respecto al Mundo",
		"Camera": "Cámara",
		"Focus Selected": "Enfocar Selección",
		"Share Camera View": "Compartir Vista de Cámara",
		"Activate Camera": "Аctivar Cámara",
		"Default Cameras": "Cámaras por defecto",
		"Orbit": "Orbitar",
		"Free": "Libre",
		"Avatar View": "Vista de avatar",
		"Navigate": "Navegar",
		"Fly": "Volar",
		"None": "Ninguna",
		"Hierarchy": "Jerarquía",
		"Link": "Enlazar",
		"Unlink": "Desenlazar",
		"Select Parent": "Seleccionar padre",
		"Grouping": "Agrupar",
		"Group": "Grupo",
		"Ungroup": "Desagrupar",
		"Open Group": "Abrir Grupo",
		"Close Group": "Cerrar Grupo",
		"Orbit Camera": "Orbitar Cámara",
		"Navigation Camera": "Cámara de Navegación",
		"Free Camera": "Cámara Libre",
		"Focus to selected object": "Enfocar Objecto Seleccionado",
		"First Person Camera": "Cámara en Primera Persona",
		"Create": "Crear",
		"Primitives": "Primitivas",
		"Sphere": "Esfera",
		"Box": "Caja",
		"Plane": "Plano",
		"Cylinder": "Cilindro",
		"Cone": "Cono",
		"Create Sphere": "Crear Esfera",
		"Create Box": "Crear Caja",
		"Create Plane": "Crear Plano",
		"Create Cylinder": "Crear Cilindro",
		"Create Cone": "Crear Cono",
		"Text": "Crear Texto",
		"Torus": "Crear Toroide",
		"Shapes": "Formas",
		"Line": "Línea",
		"Circle": "Círculo",
		"Star": "Estrella",
		"Rectangle": "Rectángulo",
		"L Section": "Sección en L",
		"T Section": "Sección en T",
		"Modifiers": "Modificadores",
		"Bend": "Doblar",
		"Twist": "Retorcer",
		"Taper": "Afilar",
		"Perlin Noise": "Ruido Perlin",
		"Simplex Noise": "Ruido Simplex",
		"Offset": "Desplazar",
		"Stretch": "Estirar",
		"Push": "Tirar",
		"UVMap": "Mapas UV",
		"Center Pivot": "Centrar pivote",
		"Extrude": "Extrudir",
		"Lathe": "Revolucionar",
		"Behaviors": "Comportamientos",
		"New Behavior": "Nuevo Comportamiento",
		"Rotator": "Rotar",
		"Orbit": "Orbitar",
		"Hyper link": "Hiperenlace",
		"Hover label": "Etiqueta Flotante",
		"Path Follow": "Seguir Trayectoria",
		"Clamp To Ground": "Afianzar al suelo",
		"LookAt": "Mirar a..",
		"Seek": "Buscar",
		"Dialog System":"Diálogo del Sistema",
		"Lights": "Luces",
		"Point": "Puntual",
		"Light": "Luz",
		"Directional": "Direccional",
		"Particles": "Partículas",
		"Basic": "Básica",
		"Cameras": "Cámaras",
		"Perspective": "Perspectiva",
		"Orthographic (comming soon!)": "Ortográfica (próximamente)",
		"Terrain": "Terreno",
		"Load Mesh URL": "Cargar Malla desde URL",
		"Tools": "Herramientas",
		"Align": "Alinear",
		"Block Painter": "Herramienta de Pintado de Bloques",
		"Spline Tools": "Herramientas de Curvas",
		"Windows": "Ventanas",
		"Chat": "Chat",
		"Users": "Usuarios",
		"Material Editor": "Editor de Materiales",
		"Script Editor": "Editor de Guiones",
		"Object Properties": "Propiedades del Objeto",
		"Models": "Modelos",
		"Inventory": "Inventario",
		"Public Inventory": "Inventario Público",
		"Show Hierarchy": "Mostrar Jerarquía",
		"Rendering": "Renderizado",
		"Toggle Wireframe": "Conmutar Vista de Alambres",
		"Toggle Glyphs": "Conmutar Mostrar Iconos",
		"Toggle Sun Shadows": "Conmutar Sombras del Sol",
		"Toggle Full Screen": "Conmutar Pantalla Completa",
		"Toggle Stats": "Сonmutar Estadísticas",
		"Toggle Interpolation": "Conmutar Interpolación",
		"Batching": "Proceso por lotes",
		"Force Batch All": "Forzar todo en Proceoso por Lotes",
		"Toggle Dynamic Batching": "Conmutar Proceso por Lotes Dinámico",
		"Location": "Posición",
		"Go to Position...": "Ir a Posición...",
		"Go to Placemark...": "Ir a Marca de Posición...",
		"Add Placemark...": "Añadir Marca de Posición...",
		"Move to ground": "Mover al Suelo",
		"Help": "Ayuda",
		"About": "Acerca de",
		"Browse All Topics...": "Mostrar Todos los Temas...",
		"Test Latency": "Comprobar Latencia",
		"Show Users Window": "Mostrar Ventana de Usuarios",
		"Show Chat Window": "Mostrar Chat",
		"Show Material Editor Window": "Mostrar Editor de Materiales",
		"Show Script Editor Window": "Mostrar Editor de Guiones",
		"Show Object Properties Window": "Mostrar Propiedades de Objeto",
		"Show Inventory Window": "Mostrar Inventario",
		"Show Hierarchy Window": "Mostrar Jerarquía"
	}
});
 
